meta:
  site_title: "NY Hacks"
  site_subtitle: "For New York developers, by New York developers"
  site_language: "en"
  absolute_baseurl: http://nyhacks.com
  domain: nyhacks.com
  author:
    full_name: Jon Gottfried
    short_name: jonmarkgo
    email: jonmarkgo@gmail.com

pygments: true
markdown: rdiscount
permalink: pretty
